=== timp/dsn-chassis/generic/lib/gwt/src/main/resources/xquestion/xquestion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <!--+
      |
      | questionnaire definition
      |
      +-->
        
  <xs:element name="questionnaire">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="model" type="QuestionnaireModelType" maxOccurs="1"/>
        <xs:element name="view" type="QuestionnaireViewType" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="repeatable" use="optional" default="no"/>      
      <xs:attribute ref="defaultPrefix" use="optional"/>      
      <xs:attribute ref="defaultNamespaceUri" use="optional"/>      
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="QuestionnaireModelType">
    <xs:sequence>
      <xs:element ref="element" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="QuestionnaireViewType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="html"/>
        <xs:element ref="label"/>
        <xs:element ref="question"/>
        <xs:element ref="questionnaire"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute ref="class"/>
  </xs:complexType>



  <!--+
      |
      | question definition
      |
      +-->
        
  <xs:element name="question">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="model" type="QuestionModelType" maxOccurs="1"/>
        <xs:element name="view" type="QuestionViewType" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute ref="repeatable" use="optional" default="no"/>      
    </xs:complexType>
    <!-- TODO key for id attribute -->
  </xs:element>

  <xs:complexType name="QuestionModelType">
    <xs:sequence>
      <xs:element ref="element" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="QuestionViewType">
    <xs:sequence>
      <!-- TODO restrict to single form control -->
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="html"/>        
        <xs:element ref="label"/>        
        <xs:element ref="input"/>        
        <xs:element ref="secret"/>        
        <xs:element ref="textarea"/>        
        <xs:element ref="select"/>        
        <xs:element ref="select1"/>        
      </xs:choice>
    </xs:sequence>
    <xs:attribute ref="class"/>
  </xs:complexType>



  <!--+
      |
      | misc
      |
      +-->
        
  <xs:attribute name="repeatable" type="YesNoType" />
  
  <xs:simpleType name="YesNoType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(yes|no)" />
    </xs:restriction>
  </xs:simpleType>

  <xs:attribute name="defaultPrefix" type="xs:NCName" />
  
  <xs:attribute name="defaultNamespaceUri" type="xs:anyURI" />
  
  <xs:element name="element">
    <xs:complexType>
      <xs:attribute name="name" type="xs:NCName" use="required"/>
      <xs:attribute name="prefix" type="xs:NCName" use="optional"/>  
      <xs:attribute name="namespaceUri" type="xs:anyURI" use="optional"/>
      <xs:attribute name="type" type="xs:NCName" use="optional" default="string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="html">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:any minOccurs="0" maxOccurs="unbounded" namespace="##any" processContents="skip"/>
      </xs:sequence>
      <xs:attribute name="readOnly" use="optional" type="ShowHideType"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="ShowHideType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(show|hide)" />
    </xs:restriction>
  </xs:simpleType>


  <xs:element name="label" type="xs:string"/>  
  <xs:element name="hint" type="xs:string"/>  

  <xs:attribute name="class" type="xs:NCName" />



  <!--+
      |
      | form controls
      |
      +-->
        
  <xs:element name="input">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="label" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="hint" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="class"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="secret">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="label" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="hint" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="class"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="textarea">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="label" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="hint" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="class"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="select" type="selectType"/>

  <xs:element name="select1" type="selectType"/>
  
  <xs:complexType name="selectType">
      <xs:sequence>
        <xs:element ref="label" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="hint" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="item" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="class"/>
      <xs:attribute name="appearance" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(full|compact|minimal)"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
  </xs:complexType>

  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="label"/>
        <xs:element ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="value" type="xs:string"/>
  
</xs:schema>

=== timp/dsn-chassis/trunk/wwarn/ui/war/submitter/study-questionnaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<questionnaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://dsn-chassis.googlecode.com/svn/trunk/generic/lib/gwt/src/main/resources/xquestion/xquestion.xsd"
	defaultPrefix="chassis" defaultNamespaceUri="http://www.cggh.org/2009/chassis/xmlns/"
	id="study">

	<model>
		<element name="study" />
	</model>

	<view>

		<questionnaire id="general">

			<model>
				<element name="general" />
			</model>

			<view class="xquestionnaire-transparent">

				<html>
					<h3>General Questions</h3>
				</html>


				<html>
					<h4 id="modulesHeading">Module(s)</h4>
				</html>

				<question id="module">
					<model>
						<element name="module" />
					</model>
					<view>
						<select appearance="full">
							<label>Please select the WWARN modules for which this study has data...</label>
							<item>
								<label>Clinical</label>
								<value>clinical</value>
							</item>
							<item>
								<label>Molecular</label>
								<value>molecular</value>
							</item>
							<item>
								<label>in vitro</label>
								<value>invitro</value>
							</item>
							<item>
								<label>Pharmacology</label>
								<value>pharmacology</value>
							</item>
						</select>
					</view>
				</question>

				<html>
					<h4 id="startend">Study Start and End</h4>
				</html>

				<question id="startDate">
					<model>
						<element name="startDate" type="date" />
					</model>
					<view>
						<input>
							<label>When did the study start?</label>
							<hint>Enter the date on which the study started, e.g., 2006-11-23.</hint>
						</input>
					</view>
				</question>

				<question id="endDate">
					<model>
						<element name="endDate" type="date" />
					</model>
					<view>
						<input>
							<label>When did the study end?</label>
							<hint>Enter the year in which the study ended, e.g., 2008-06-30, or leave blank if the study
								is ongoing.
							</hint>
						</input>
					</view>
				</question>

				<html>
					<h4 id="pi">Principal Investigator(s)</h4>
				</html>

				<questionnaire id="principalInvestigator" repeatable="yes">

					<model>
						<element name="principalInvestigator" />
					</model>

					<view>

						<html readOnly="hide">
							<p>Who was the principal investigator of this study?</p>
						</html>

						<question id="principalInvestigator-name">
							<model>
								<element name="name" />
							</model>
							<view>
								<input>
									<label>Name?</label>
								</input>
							</view>
						</question>

						<question id="principalInvestigator-email" repeatable="yes">
							<model>
								<element name="email" />
							</model>
							<view>
								<input>
									<label>Email address?</label>
								</input>
							</view>
						</question>

						<question id="principalInvestigator-uri" repeatable="yes">
							<model>
								<element name="uri" />
							</model>
							<view>
								<input>
									<label>Home page?</label>
									<hint>Enter the URL of a web page that is the person's home page.</hint>
								</input>
							</view>
						</question>

						<question id="principalInvestigator-org" repeatable="yes">
							<model>
								<element name="org" />
							</model>
							<view>
								<input>
									<label>Host organisation or institution?</label>
									<hint>Enter the name of the person's host organisation or institution.</hint>
								</input>
							</view>
						</question>

						<html readOnly="hide">
							<p>
								<em>You can add another principal investigator by clicking the
									"+" button below.
								</em>
							</p>
						</html>

					</view>

				</questionnaire>


				<html>
					<h4 id="pathogens">Pathogen Species</h4>
				</html>

				<question id="pathogenSpecies">
					<model>
						<element name="pathogenSpecies" />
					</model>
					<view>
						<select appearance="full">
							<label>What pathogen species were studied?</label>
							<item>
								<label>P. falciparum</label>
								<value>plasmodiumfalciparum</value>
							</item>
							<item>
								<label>P. vivax</label>
								<value>plasmodiumvivax</value>
							</item>
							<item>
								<label>P. ovale</label>
								<value>plasmodiumovale</value>
							</item>
							<item>
								<label>P. malariae</label>
								<value>plasmodiummalariae</value>
							</item>
							<item>
								<label>P. knowlesi</label>
								<value>plasmodiumknowlesi</value>
							</item>
						</select>
					</view>
				</question>

				<html>
					<h4 id="sites">Study Site(s)</h4>
				</html>

				<questionnaire id="site" repeatable="yes">

					<model>
						<element name="site" />
					</model>

					<view>

						<html readOnly="hide">
							<p>Describe the site (location) where study subjects were
								recruited from...
							</p>
						</html>

						<question id="site-country">
							<model>
								<element name="country" />
							</model>
							<view>
								<select1 appearance="minimal">
									<label>Country?</label>
									<items
										src="/chassis-wwarn-ui/submitter/countries.en.xml" />
								</select1>
							</view>
						</question>

						<question id="site-region">
							<model>
								<element name="region" />
							</model>
							<view>
								<input>
									<label>Region?</label>
								</input>
							</view>
						</question>

						<question id="site-district">
							<model>
								<element name="district" />
							</model>
							<view>
								<input>
									<label>District?</label>
								</input>
							</view>
						</question>

						<question id="site-locality">
							<model>
								<element name="locality" />
							</model>
							<view>
								<input>
									<label>Locality?</label>
								</input>
							</view>
						</question>

						<html readOnly="hide">
							<p style="display: block;">
								<em>If the study involves more than one site, what identifier
									(i.e., code) is used for this site in the submitted study data?
								</em>
							</p>
						</html>

						<question id="siteId">
							<model>
								<element name="identifier" />
							</model>
							<view>
								<input>
									<label>Study site code?</label>
								</input>
							</view>
						</question>

						<html readOnly="hide">
							<p>
								<em>You can add another site by clicking the "+" button below.</em>
							</p>
						</html>

					</view>

				</questionnaire>


				<html>
					<h4 id="pubs">Publications</h4>
				</html>

				<questionnaire id="publication" repeatable="yes">

					<model>
						<element name="publication" />
					</model>

					<view>
						<html readOnly="hide">
							<p>Is this study described in any published research papers?</p>
						</html>

						<question id="publication-title">
							<model>
								<element name="title" />
							</model>
							<view>
								<input>
									<label>Title?</label>
								</input>
							</view>
						</question>

						<question id="publication-year">
							<model>
								<element name="year" />
							</model>
							<view>
								<input>
									<label>Year?</label>
								</input>
							</view>
						</question>

						<question id="publication-journal">
							<model>
								<element name="journal" />
							</model>
							<view>
								<input>
									<label>Journal?</label>
								</input>
							</view>
						</question>

						<question id="publication-link" repeatable="yes">
							<model>
								<element name="uri" />
							</model>
							<view>
								<input>
									<label>Web link?</label>
								</input>
							</view>
						</question>

						<question id="publication-doi">
							<model>
								<element name="doi" />
							</model>
							<view>
								<input>
									<label>DOI?</label>
								</input>
							</view>
						</question>

						<html readOnly="hide">
							<p>
								<em>You can add another publication by clicking the "+" button
									below.
								</em>
							</p>
						</html>

					</view>

				</questionnaire>

			</view>

		</questionnaire>


		<!--
				+ | | BEGIN CLINICAL QUESTIONNAIRE | +
			-->

		<questionnaire defaultPrefix="wwarn"
			defaultNamespaceUri="http://www.cggh.org/2009/chassis/wwarn/xmlns"
			id="wwarn-clinical" >

			<model>
				<element name="clinical" />
				<relevant path="../general/module" comparator="contains" value="clinical"/>
			</model>

			<view class="xquestionnaire-transparent">

				<html>
					<h3 id="clinical">WWARN Clinical Module Questions</h3>
				</html>

 				<html><h4 id="wwarn-clinical-publication">Publication</h4></html>
 				
 				<questionnaire id="wwarn-clinical-publication">
 					<model>
 						<element name="publication"/>
 					</model>
 					<view>
 						<question id="wwarn-clinical-publication-registrationUrl">
 							<model>
 								<element name="registrationUrl"/>
 							</model>
 							<view>
 								<input>
 									<label>Registration URL with clinicaltrials.gov?</label>
 								</input>
 							</view>
 						</question>
 						<question id="wwarn-clinical-publication-embargoDate">
 							<model>
 								<element name="embargoDate" type="date"/>
 							</model>
 							<view>
 								<input>
 									<label>When can data be put on web? </label>
 								</input>
	 							<inlinehtml>(embargo date)</inlinehtml>
 							</view>
 						</question>
 					
 					</view>
 				</questionnaire>			
<!-- 

							<a href="#wwarn-clinical-inclusionExclusionCriteria">Inclusion/Exclusion Criteria</a>
 -->
 				<html><h4 id="wwarn-clinical-treatments">Treatments</h4></html>
 				
 				<questionnaire id="wwarn-clinical-treatments">
 					<model>
 						<element name="treatments"/>
 					</model>
 					<view>
 						<html><h5>Treatment regimens</h5></html>
 						<questionnaire id="wwarn-clinical-treatments-regimen" repeatable="yes">
 							<model>
 								<element name="regimen"/>
